{% set version = "0.3.1" %}

package:
  name: nbexamples
  version: {{ version }}

source:
  url: https://github.com/danielballan/nbexamples/archive/v{{ version }}.tar.gz
  sha256: ec2d08f618ad40718932a1fe1f2ca019c8bcd9b845f4eab360e69464b76a7c99

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - notebook >=4.2.0
  run:
    - nbconvert
    - nbformat
    - notebook >=4.2.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - nbexamples

about:
  home: https://github.com/danielballan/nbexamples
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Notebook extension that shows a list of example notebooks for users to preview and clone

extra:
  recipe-maintainers:
    - danielballan
    - ericdill
    - mariusvniekerk
    - parente
